"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local .env file into the environment for development. On the VPS the
# same variables are provided by systemd (EnvironmentFile), so this is a no-op
# there (load_dotenv does not override variables already set).
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment (set via the server's .env file). The fallback is a
# throwaway dev key -- override it in production by setting DJANGO_SECRET_KEY.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-change-me',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False; set DJANGO_DEBUG=True in your local .env for development.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    '134.209.66.211,localhost,127.0.0.1',
).split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    # Local
    'api',
]

# Django REST Framework: reuse the session login that already guards /admin/,
# so being logged in to the dashboard authenticates same-origin API calls too.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Session auth powers the browsable API + dashboard (same login as /admin/).
        'rest_framework.authentication.SessionAuthentication',
        # Token auth is for API clients like Postman/curl/mobile. Both header
        # styles work:  Authorization: Token <key>   or   Bearer <key>
        'rest_framework.authentication.TokenAuthentication',
        'api.authentication.BearerTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # drf-spectacular generates the OpenAPI schema that powers /api/docs/.
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# OpenAPI / Swagger documentation (drf-spectacular).
SPECTACULAR_SETTINGS = {
    'TITLE': 'HMS API',
    'DESCRIPTION': (
        'REST API for the House Management System — properties, tenants, rent '
        'payments and contact messages.\n\n'
        '**Authentication:** POST your username + password to '
        '`/api/auth/login/` to get an API token, then send it in the '
        '`Authorization` header as either `Token <key>` or `Bearer <key>`. '
        '(You can also mint a token with `python manage.py drf_create_token '
        '<username>`, and browser sessions from the /admin/ login are accepted.)'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,  # don't expose the raw schema on the Swagger page
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files (e.g. the admin CSS) directly from gunicorn
    # so they work with DEBUG=False without needing a separate nginx location.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# The dashboard at /admin/ is @login_required; send anonymous users to the
# built-in admin login (now mounted at /django-admin/login/). Using the URL
# name means the reverse respects any sub-path prefix in production.
LOGIN_URL = 'admin:login'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Project-level templates are searched first, so admin/login.html here
        # overrides Django's built-in admin login page.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Uses MySQL when DJANGO_DB_ENGINE=mysql; otherwise falls back to a local
# SQLite file. Both the live site and local dev point at the SAME MySQL
# database -- the live site connects on the VPS loopback, and local dev
# connects through an SSH tunnel (see DEPLOYMENT.md) so the DB stays private.
if os.environ.get('DJANGO_DB_ENGINE') == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DJANGO_DB_NAME', 'mysite'),
            'USER': os.environ.get('DJANGO_DB_USER', 'mysite'),
            'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', ''),
            'HOST': os.environ.get('DJANGO_DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DJANGO_DB_PORT', '3306'),
            'CONN_MAX_AGE': int(os.environ.get('DJANGO_DB_CONN_MAX_AGE', '60')),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL is env-driven so the app can live under a URL sub-path in
# production. On the VPS the app is served under /mysite/ (nginx sets
# SCRIPT_NAME=/mysite), so the browser must request assets at
# /mysite/static/... -- set DJANGO_STATIC_URL=/mysite/static/ there.
# Locally the app runs at the site root, so the default /static/ is correct.
STATIC_URL = os.environ.get('DJANGO_STATIC_URL', 'static/')
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Project-level static assets (the vendored NiceAdmin dashboard template lives
# here). collectstatic gathers these into STATIC_ROOT for WhiteNoise to serve in
# production; the runserver dev server picks them up directly via the finders.
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise serves files under the path part of STATIC_URL by default. When
# STATIC_URL carries the /mysite/ prefix but nginx has already stripped
# SCRIPT_NAME, WhiteNoise still sees /static/..., so point it there explicitly
# (set DJANGO_WHITENOISE_STATIC_PREFIX=/static/ on the server).
if os.environ.get('DJANGO_WHITENOISE_STATIC_PREFIX'):
    WHITENOISE_STATIC_PREFIX = os.environ['DJANGO_WHITENOISE_STATIC_PREFIX']

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
